{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.serviceName }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  {{- if .Values.configmap.data }}
{{ toYaml .Values.configmap.data | indent 2 }}
  {{- end }}
{{- end }} 
