apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.serviceName }}
  metrics:
    {{- if .Values.hpa.metrics }}
{{ toYaml .Values.hpa.metrics | indent 4 }}
    {{- end }}
