{{- if .Values.deployment.containers.env.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serviceName }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if .Values.secret.data }}
{{ toYaml .Values.secret.data | indent 2 }}
  {{- end }}
{{- end }}
