{{- if .Values.deployment.containers.env.secret.enabled }}

{{- if .Values.secret.isSealedSecrets }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.serviceName }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    {{- if .Values.secret.data }}
{{ toYaml .Values.secret.data | indent 4 }}
    {{- end }}
  template:
    metadata:
      name: {{ .Values.serviceName }}-secret
      namespace: {{ .Release.Namespace }}

{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serviceName }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if .Values.secret.data }}
{{ toYaml .Values.secret.data | indent 2 }}
  {{- end }}

{{- end }}

{{- end }}
